version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  gateway:
    image: gateway
    build: ./gateway/
    ports:
      - "8080:80"
    environment:
      - CARS=cars:80
      - PAYMENT=payment:80
      - RENTAL=rental:80

  cars:
    image: cars
    build: ./rsoi_lr2/
    ports:
      - "8070:80"
    environment:
      - DBHOST=postgres
      - DBPORT=5432
      - DATABASE=cars
      - USERNAME=program
      - PASSWORD=test

  rental:
    image: rental
    build: ./rental/
    ports:
      - "8060:80"
    environment:
      - DBHOST=postgres
      - DBPORT=5432
      - DATABASE=rental
      - USERNAME=program
      - PASSWORD=test

  payment:
    image: payment
    build: ./payment/
    ports:
      - "8050:80"
    environment:
      - DBHOST=postgres
      - DBPORT=5432
      - DATABASE=payments
      - USERNAME=program
      - PASSWORD=test

  


volumes:
  db-data: